### ISSUE TITLE
Needs native `disabled` support

### ISSUE THREAD

**Issue by tomayac** [GoogleChromeLabs/input-knob#1]
Currently, setting the `<input-knob>` to `disabled` has no effect, and one has to emulate it poorly:

```css
input-knob[disabled] {  
  pointer-events: none;
  opacity: .25;
}
```

This [doesn't feel right](https://glitch.com/edit/#!/dark-mode-knob?path=style.css:38:1).
